import test from 'node:test';
import assert from 'node:assert/strict';
import {parseChatResponse,terminalChat} from '../src/terminal-chat.mjs';
test('optional null model fields do not break ordinary answers',()=>{assert.deepEqual(parseChatResponse('```json\n{"action":"EXPLAIN","reply":"Liquidity earns swap fees while active.","amountUsdc":null,"widthPct":null}\n```'),{action:'EXPLAIN',reply:'Liquidity earns swap fees while active.'});});
test('bad replies and signing actions stay rejected with a useful error',()=>{for(const content of ['bad','null','{"action":"SIGN","reply":"Done"}','{"action":"EXPLAIN"}'])assert.throws(()=>parseChatResponse(content),e=>e.expose&&e.status===503&&/invalid response/.test(e.message));});
test('provider timeout, authentication and rate limit errors are distinct and never expose provider bodies',async()=>{const old=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY='test';try{for(const [fetcher,pattern] of [[async()=>{throw Object.assign(Error('secret'),{name:'TimeoutError'});},/timed out/],[async()=>({ok:false,status:401}),/credentials/],[async()=>({ok:false,status:429}),/busy/]])await assert.rejects(terminalChat({message:'Explain LP fees.'},{fetcher}),e=>e.expose&&pattern.test(e.message)&&!e.message.includes('secret'));}finally{if(old===undefined)delete process.env.DEEPSEEK_API_KEY;else process.env.DEEPSEEK_API_KEY=old;}});
test('explanations ignore draft fields and cannot accidentally edit the page',()=>{assert.deepEqual(parseChatResponse('{"action":"EXPLAIN","reply":"The position is in range.","amountUsdc":0,"widthPct":"unused"}'),{action:'EXPLAIN',reply:'The position is in range.'});assert.throws(()=>parseChatResponse('{"action":"EDIT","reply":"Update","amountUsdc":0}'));});
test('invalid or truncated model answers are repaired once before returning to the UI',async()=>{const old=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY='test';try{for(const bad of [{message:{content:'{"action":"ANSWER","reply":"In range"}'},finish_reason:'stop'},{message:{content:'{"action":"EXPLAIN","reply":"cut'},finish_reason:'length'}]){let n=0;const result=await terminalChat({message:'Explain LP ranges.'},{fetcher:async(_u,opts)=>{const payload=JSON.parse(opts.body);if(n)assert.match(payload.messages.at(-1).content,/output format check/);return {ok:true,json:async()=>({choices:[n++?{message:{content:'{"action":"EXPLAIN","reply":"LP ranges define where liquidity is active."}'},finish_reason:'stop'}:bad]})};}});assert.equal(n,2);assert.equal(result.action,'EXPLAIN');}}finally{if(old===undefined)delete process.env.DEEPSEEK_API_KEY;else process.env.DEEPSEEK_API_KEY=old;}});
test('repeated malformed outputs stop after two requests and never produce actions',async()=>{const old=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY='test';let n=0;try{await assert.rejects(terminalChat({message:'Explain fees.'},{fetcher:async()=>{n++;return {ok:true,json:async()=>({choices:[{message:{content:'{"action":"SIGN","reply":"done"}'}}]})};}}),/automatic retry/);assert.equal(n,2);}finally{if(old===undefined)delete process.env.DEEPSEEK_API_KEY;else process.env.DEEPSEEK_API_KEY=old;}});
