import test from 'node:test';import assert from 'node:assert/strict';
import {validateFresh,validatePositionId,readPool,readPosition,readHistory,validateGraph} from '../src/data.mjs';
import {POOL,USDC,WETH} from '../src/config.mjs';
test('freshness fails closed for old and future blocks',()=>{validateFresh(1000,1100);assert.throws(()=>validateFresh(1000,1200));assert.throws(()=>validateFresh(1200,1000));});
test('ID validation preserves literal tokens',()=>{assert.equal(validatePositionId('123'),123n);for(const x of ['0','01',' 1','1e3','-1','0x12','1.1',null,{},'9'.repeat(78)])assert.throws(()=>validatePositionId(x));});
test('wrong chain rejected before contract reading',async()=>{await assert.rejects(()=>readPool({getChainId:async()=>8453,getBlock:async()=>({timestamp:BigInt(Math.floor(Date.now()/1000))})}),/Wrong RPC chain/);});
test('wrong-pool NFT rejected',async()=>{await assert.rejects(()=>readPosition('1',{blockNumber:'100'},{readContract:async()=>[0,'',WETH,USDC,3000]}),/supported/);});
test('Graph missing config and upstream failures are explicit without leaking key',async()=>{const prev=process.env.GRAPH_API_KEY;try{delete process.env.GRAPH_API_KEY;assert.equal((await readHistory({})).status,'not_configured');process.env.GRAPH_API_KEY='test-secret';const r=await readHistory({},async()=>{throw new Error('test-secret')});assert.equal(r.status,'unavailable');assert.ok(!JSON.stringify(r).includes('test-secret'));}finally{if(prev===undefined)delete process.env.GRAPH_API_KEY;else process.env.GRAPH_API_KEY=prev;}});
test('Graph pinned block, price and historical metrics are validated',()=>{const now=1750000000;const state={blockNumber:'100',blockHash:'0xabc',sqrtPriceX96:'123',tick:3};const data={_meta:{block:{number:100,hash:'0xabc'},hasIndexingErrors:false},pool:{id:POOL,token0:{id:USDC},token1:{id:WETH},feeTier:'3000',sqrtPrice:'123',tick:'3'},poolDayDatas:[{date:now-1000,volumeUSD:'10',tvlUSD:'100',feesUSD:'0.03'}]};assert.equal(validateGraph(data,state,now).status,'verified');for(const mutate of [d=>d._meta.hasIndexingErrors=true,d=>d._meta.block.hash='0xdef',d=>d.pool.sqrtPrice='124',d=>d.poolDayDatas[0].volumeUSD='NaN',d=>d.poolDayDatas=[]]) {const d=structuredClone(data);mutate(d);assert.throws(()=>validateGraph(d,state,now));}});
