import test from 'node:test';
import assert from 'node:assert/strict';
import {createPoolCatalog} from '../src/pool-catalog.mjs';
import {NETWORK} from '../src/testnet.mjs';
const other='0x1111111111111111111111111111111111111111',zero='0x'+'0'.repeat(40);
function client({mismatch=false,fail=false}={}){return {getBlock:async()=>({number:20000n,timestamp:BigInt(Math.floor(Date.now()/1000))}),getChainId:async()=>84532,getLogs:async()=>[],readContract:async({address,functionName,args,blockNumber})=>{assert.equal(blockNumber,20000n);if(fail)throw Error('RPC unavailable');switch(functionName){case 'getPool':return args[2]===500?(mismatch?zero:NETWORK.pool):args[2]===3000?other:zero;case 'token0':return NETWORK.usdc;case 'token1':return NETWORK.weth;case 'fee':return address===other?3000:500;case 'slot0':return [BigInt(Math.floor(Math.sqrt(1e12/2000)*2**96)),0];case 'liquidity':return 1n;case 'symbol':return address===NETWORK.usdc?'USDC':'WETH';case 'decimals':return address===NETWORK.usdc?6:18;case 'balanceOf':return address===NETWORK.usdc?2000000n:1000000000000000n;default:throw Error(functionName);}}};}
test('catalog normalizes token decimals, verifies pools and restricts execution to the demo pool',async()=>{const c=createPoolCatalog(client()),r=await c.discover();assert.equal(r.items.length,2);assert.equal(r.items[0].executable,true);assert.equal(r.items[1].executable,false);assert.ok(Math.abs(r.items[0].price-2000)<.00001);assert.equal(r.items[0].tokens[0].balance,'2');assert.equal(r.items[0].quote,'USDC');assert.equal(await c.discover(),r);});
test('catalog excludes a pool whose factory identity does not match',async()=>{const r=await createPoolCatalog(client({mismatch:true})).discover();assert.equal(r.items.length,1);assert.equal(r.items[0].address,other);assert.equal(r.discoveryLimited,true);});
test('RPC failures never become a successful empty list',async()=>{await assert.rejects(createPoolCatalog(client({fail:true})).discover(),/temporarily unavailable/);});
