import test from 'node:test';import assert from 'node:assert/strict';
import {createRequire} from 'node:module';const {TickMath}=createRequire(import.meta.url)('@uniswap/v3-sdk');
import {createApp} from '../server.mjs';
async function withApp(deps,run){const s=createApp(deps);await new Promise(r=>s.listen(0,'127.0.0.1',r));try{await run(`http://127.0.0.1:${s.address().port}`);}finally{await new Promise(r=>s.close(r));}}
const fixture=()=>({sqrtPriceX96:TickMath.getSqrtRatioAtTick(196200).toString(),tick:196200,liquidity:'1000000000000000000',blockTimestamp:Math.floor(Date.now()/1000),blockNumber:'100'});
const deps={client:()=>null,readPool:async()=>fixture(),readHistory:async()=>({status:'not_configured'}),readPosition:async()=>{throw new Error('not found');}};
const post=(url,body,headers={})=>fetch(url+'/api/analyze',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
test('HTTP loop supports learning, fails invalid import and never exposes transaction endpoints',async()=>withApp(deps,async url=>{const r=await post(url,{mode:'learning'});assert.equal(r.status,200);const b=await r.json();assert.equal(b.execution,'disabled');assert.equal(b.result.position.kind,'hypothetical');assert.equal(b.result.candidates.length,3);assert.equal((await post(url,{mode:'nft',tokenId:'1e3'})).status,400);assert.equal((await post(url,{mode:'nft',tokenId:'123'})).status,422);assert.equal((await post(url,{mode:'learning',rpcUrl:'http://localhost'})).status,400);assert.equal((await post(url,{mode:'learning'},{Origin:'http://evil.example'})).status,403);assert.equal((await fetch(url+'/api/send')).status,404);assert.equal((await fetch(url+'/app.js')).status,200);}));
test('provider failure does not return fixtures or credential-bearing errors',async()=>withApp({...deps,readPool:async()=>{throw new Error('https://rpc.test/secret-key');}},async url=>{const r=await post(url,{mode:'learning'});assert.equal(r.status,503);const b=await r.text();assert.ok(!b.includes('secret-key'));assert.ok(b.includes('No sample data'));}));
