import {spawnSync} from 'node:child_process';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {openSimulation} from '../src/simulation.mjs';
const policy={action:'POLICY',maxCapital:100000,maxFee:500,maxDaily:10,maxSlippageBps:100,expiresInMinutes:60,automatic:true};
function harness(path=':memory:'){let time=Date.now();let db=openSimulation(path,{clock:()=>time});const id=db.create();return {get db(){return db;},id,send:(action,extra={})=>db.command(id,{requestId:randomUUID(),action,...extra}),ticks(n=1){for(let i=0;i<n;i++){time+=1000;db.tick();}},advance(ms){time+=ms;},state:()=>db.get(id),ready(){this.send('FUND',{amount:100000});this.ticks(2);this.send('POLICY',policy);},reopen(){db.close();db=openSimulation(path,{clock:()=>time});},close(){db.close();}};}
test('simulation only: fund, mint, increase, partial reduce, collect, rebalance and exit conserve ledger',()=>{
 const h=harness();try{h.ready();h.send('ENTER',{amount:70000});h.ticks(3);assert.equal(h.state().deployed,70000);h.send('INCREASE',{amount:10000});h.ticks();assert.equal(h.state().deployed,80000);h.send('DECREASE',{amount:10000});h.ticks();assert.equal(h.state().deployed,70000);h.send('ACCRUE');h.send('COLLECT');h.ticks();assert.equal(h.state().unclaimed,0);h.send('REBALANCE');h.ticks(5);assert.equal(h.state().positionNumber,2);h.send('EXIT');h.ticks(2);const s=h.state();assert.equal(s.deployed,0);assert.equal(s.cash,99700);assert.equal(s.realExecution,false);assert.equal(s.mode,'SIMULATION');assert.ok(!JSON.stringify(s).includes('0x'));}finally{h.close();}
});
test('partial failure survives DB restart; resumes once without repeating REMOVE or collecting twice',()=>{
 const dir=mkdtempSync(join(tmpdir(),'lp-simulation-')),h=harness(join(dir,'sim.sqlite'));try{h.ready();h.send('ENTER',{amount:80000});h.ticks(3);h.send('ACCRUE');h.send('REBALANCE');h.send('FAIL',{phase:'COLLECT'});h.ticks(2);assert.equal(h.state().job.status,'BLOCKED');assert.equal(h.state().deployed,0);assert.equal(h.state().unclaimed,300);const cash=h.state().cash;h.reopen();assert.equal(h.state().cash,cash);h.send('RESUME');h.ticks(4);const s=h.state();assert.equal(s.job.status,'COMPLETE');assert.equal(s.deployed,80000);assert.equal(s.cash,19900);assert.equal(s.events.filter(e=>e.detail.includes(s.job.id+' REMOVE')).length,1);}finally{h.close();rmSync(dir,{recursive:true,force:true});}
});
test('revocation, pause, expiry and changed price stop later phases; recovery keeps actual intermediate simulated state',()=>{
 const h=harness();try{h.ready();h.send('ENTER',{amount:80000});h.ticks(3);h.send('REBALANCE');h.ticks();h.send('REVOKE');h.ticks(10);assert.equal(h.state().deployed,0);assert.equal(h.state().job.status,'BLOCKED');assert.throws(()=>h.send('RESUME'),/revoked/);h.send('RECOVER');assert.equal(h.state().cash,99800);h.send('POLICY',{...policy,expiresInMinutes:1});h.send('ENTER',{amount:80000});h.advance(61000);h.ticks();assert.match(h.state().job.reason,/expired/);h.send('RECOVER');h.send('POLICY',policy);h.send('ENTER',{amount:80000});h.send('PRICE',{price:4000});h.ticks();assert.match(h.state().job.reason,/slippage/);h.send('RECOVER');h.send('POLICY',policy);h.send('ENTER',{amount:80000});h.send('PAUSE');assert.throws(()=>h.send('RESUME'),/paused/);}finally{h.close();}
});
test('automatic observer has cooldown, durable daily limits, no duplicate in-flight jobs',()=>{
 const h=harness();try{h.ready();h.send('ENTER',{amount:80000});h.ticks(3);h.send('PRICE',{price:3500});h.ticks(5);assert.equal(h.state().job.kind,'ENTER');h.advance(60000);h.ticks();assert.equal(h.state().job.kind,'REBALANCE');assert.equal(h.state().job.automatic,true);h.ticks(5);assert.equal(h.state().positionNumber,2);h.send('POLICY',{...policy,maxDaily:2});h.send('PRICE',{price:4500});h.advance(60000);h.ticks(4);assert.equal(h.state().positionNumber,2);assert.equal(h.state().events.at(-1).event,'MONITOR_SKIPPED');}finally{h.close();}
});
test('replay, identity isolation, malformed requests, policy and fee limits fail closed',()=>{
 const h=harness();try{const id2=h.db.create(),input={requestId:randomUUID(),action:'FUND',amount:100000};h.db.command(h.id,input);h.ticks(2);h.db.command(h.id,input);h.ticks(2);assert.equal(h.state().cash,100000);assert.equal(h.db.get(id2).cash,0);assert.throws(()=>h.db.command(h.id,{...input,amount:200000}),/reused/);assert.throws(()=>h.send('FUND',{amount:NaN}),/Funding/);assert.throws(()=>h.send('ENTER',{amount:10000}),/Policy/);h.send('POLICY',{...policy,maxFee:0});assert.throws(()=>h.send('ENTER',{amount:10000}),/Fee/);h.send('POLICY',{...policy,maxCapital:100});assert.throws(()=>h.send('ENTER',{amount:1000}),/Capital/);h.send('POLICY',policy);assert.throws(()=>h.send('ENTER',{amount:100001}),/Insufficient/);assert.throws(()=>h.send('FUND',{amount:100,address:'0xabc'}),/fields/);assert.throws(()=>h.send('EXIT',{amount:100}),/parameters/);assert.throws(()=>h.db.get('bad'),/Unknown/);}finally{h.close();}
});
test('SIGKILL after a committed phase restores the next phase without duplicate debit',()=>{
 const dir=mkdtempSync(join(tmpdir(),'lp-simulation-kill-')),path=join(dir,'sim.sqlite'),h=harness(path);
 try{h.ready();h.send('ENTER',{amount:80000});h.ticks(3);h.send('REBALANCE');
  const code=`import {openSimulation} from ${JSON.stringify(new URL('../src/simulation.mjs',import.meta.url).href)};const db=openSimulation(process.argv[1]);db.tick();process.kill(process.pid,'SIGKILL');`;
  const child=spawnSync(process.execPath,['--input-type=module','-e',code,path]);assert.equal(child.signal,'SIGKILL');
  assert.equal(h.state().job.phase,1);assert.equal(h.state().deployed,0);h.reopen();h.ticks(4);assert.equal(h.state().job.status,'COMPLETE');assert.equal(h.state().deployed,80000);assert.equal(h.state().cash,19600);assert.equal(h.state().positionNumber,2);
 }finally{h.close();rmSync(dir,{recursive:true,force:true});}
});
test('two SQLite handles commit each mock phase exactly once',()=>{
 const dir=mkdtempSync(join(tmpdir(),'lp-simulation-')),path=join(dir,'sim.sqlite'),h=harness(path);let second;try{h.ready();h.send('ENTER',{amount:80000});second=openSimulation(path);h.ticks();second.tick();h.ticks();second.tick();assert.equal(h.state().positionNumber,1);assert.equal(h.state().deployed,80000);assert.equal(h.state().feesSpent,200);}finally{second?.close();h.close();rmSync(dir,{recursive:true,force:true});}
});
