import {ensureSignerAttached} from './signer-attachment.mjs';
import React,{useEffect,useRef,useState} from 'react';
import {useSigners} from '@privy-io/react-auth';
export function ExecutePlan({plan,api,onUpdate}){
 const {addSigners,removeSigners}=useSigners();
 const [record,setRecord]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const cleaned=useRef(false),working=useRef(false);
 useEffect(()=>{let live=true;async function poll(){try{const {items}=await api('management/list');const m=items.find(m=>m.proposal?.plan.id===plan.id);if(live&&m){setRecord(m);onUpdate({...m.proposal.plan,accessCleanupPending:!!(m.executionOnly||m.session)&&m.status==='COMPLETED'&&!m.signerRemovedAt});}}catch(e){if(live)setError(e.message);}}poll();const timer=plan.discardedAt||plan.calls.every(c=>c.status==='confirmed')||Date.now()>=plan.deadline*1000?null:setInterval(poll,5000);return()=>{live=false;clearInterval(timer);};},[plan.id]);
 useEffect(()=>{if(!(record?.executionOnly||record?.session)||!(record.status==='COMPLETED'||plan.discardedAt&&['PAUSED','REVOKED'].includes(record.status))||record.signerRemovedAt||cleaned.current)return;cleaned.current=true;(async()=>{try{const check=await api('management/cleanup-check',{id:record.id});if(!check.exclusive)throw Error('Operation complete. Signing key retired; shared wallet access was preserved.');await removeSigners({address:plan.wallet});const ended=await api('management/signer-removed',{id:record.id});setRecord(ended);onUpdate({...ended.proposal.plan,accessCleanupPending:false});}catch(e){setError(e.message);}})();},[record?.status,record?.signerRemovedAt,plan.discardedAt]);
 async function execute(){if(working.current)return;working.current=true;setBusy(true);setError('');try{const m=await api('management/authorize-operation',{id:plan.id});setRecord(m);await ensureSignerAttached({api,addSigners,wallet:plan.wallet,record:m});setRecord(await api('management/activate',{id:m.id,trigger:'OPERATOR'}));}catch(e){setError(e.message);}finally{setBusy(false);working.current=false;}}
 const complete=plan.calls.every(c=>c.status==='confirmed'),waiting=record?.status==='WATCHING'&&record.job?.status==='ARMED',running=record?.status==='WATCHING'&&['QUEUED','RUNNING'].includes(record.job?.status),expired=Date.now()>=plan.deadline*1000,started=plan.calls.some(c=>c.hash||c.status==='awaiting_wallet');
 if((complete||plan.discardedAt)&&!(record?.executionOnly||record?.session))return null;
 return <section className="execute-plan" aria-label="Automatic operation"><h3>{complete?'Operation complete':waiting?'Authorized · waiting for AI':running?'Completing your operation…':record?.status==='PAUSED'?'Operation paused':'Confirm this operation'}</h3><p><strong>{plan.details.usdc?`${plan.details.usdc} USDC + ${plan.details.weth} WETH`:plan.action}</strong>{plan.details.low&&<> · Range {Number(plan.details.low).toFixed(2)}–{Number(plan.details.high).toFixed(2)} USDC/WETH</>}</p><p>{complete?'All transactions confirmed.': 'Review this plan. One limited wallet authorization lets Copilot handle every transaction in order.'}</p>{complete&&<p className="small-note">{record?.signerRemovedAt?'Temporary signing access removed.':'Finishing temporary access cleanup…'}</p>}<p className="small-note">Base Sepolia · this plan only · expires {new Date(plan.deadline*1000).toLocaleTimeString('en-US')} · total gas cap 0.0003 ETH</p>{!complete&&!waiting&&!running&&!plan.discardedAt&&!started&&!expired&&<button className="primary wide" disabled={busy||!!record?.job||record&&record.status!=='WATCHING'} onClick={execute}>{busy?'Preparing wallet authorization…':'Confirm & complete automatically →'}</button>}{waiting&&<p role="status">No transactions sent. AI has not requested this adjustment yet.</p>}{running&&<><progress value={plan.calls.filter(c=>c.status==='confirmed').length} max={plan.calls.length}/><p role="status">{plan.calls.filter(c=>c.status==='confirmed').length} of {plan.calls.length} transactions confirmed. You can leave this page open while the server completes the operation.</p></>}{record?.status==='PAUSED'&&<p className="small-note">A check stopped execution. Confirmed transactions remain recorded. Review recovery details below before continuing.</p>}{expired&&!complete&&<p className="small-note">This plan expired. Create a new preview.</p>}{error&&<p className="error-banner" role="alert">{error}</p>}</section>;
}
