import React,{useState,useEffect} from 'react';
export function Funding({account,getAccessToken}){
 const [quote,setQuote]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 async function submit(e){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setQuote(null);setError('');
 try{const token=await getAccessToken();if(!token)throw Error('Sign in again.');const amount=f.get('amount');if(!/^\d+$/.test(amount))throw Error('Use whole USDC.');
 const r=await fetch('/api/funding-quote',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({wallet:f.get('wallet'),chainId:Number(f.get('chainId')),amount:(BigInt(amount)*1000000n).toString()})});const data=await r.json();if(!r.ok)throw Error(data.error);setQuote(data);
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section aria-label="Funding quote"><h3>LI.FI funding quote — read only</h3><p>Native USDC on Arbitrum or Base → Ethereum, same linked recipient. No transaction or approval is sent. Requesting a quote shares the selected address and amount with LI.FI.</p><form onSubmit={submit} onChange={()=>setQuote(null)}><fieldset disabled={busy}><label>Wallet<select name="wallet">{account.wallets.map(w=><option key={w.address} value={w.address}>{w.address}</option>)}</select></label><label>Source chain<select name="chainId"><option value="42161">Arbitrum</option><option value="8453">Base</option></select></label><label>Whole USDC<input name="amount" type="number" min="1" max="10000" step="1" defaultValue="100" required/></label><button disabled={busy||!account.wallets.length}>{busy?'Getting quote…':'Get / refresh live quote'}</button></fieldset></form>{error&&<p role="alert">{error}</p>}{quote&&<div><strong>{now-quote.fetchedAt>=quote.refreshAfterMs?'STALE — refresh required':'LIVE QUOTE — execution disabled'}</strong><p>Expected {Number(quote.toAmount)/1e6} USDC · minimum {Number(quote.toAmountMin)/1e6} USDC · {quote.tool}</p><p>{quote.notice}</p></div>}</section>;
}
