import {ensureSignerAttached} from './signer-attachment.mjs';
import {fmt} from './PoolViews.jsx';
import {useSigners} from '@privy-io/react-auth';
import React,{useEffect,useState,useRef} from 'react';
export function Management({account,wallet,tokenId,api,command,isActive,onComplete,onSimulation,onStatus,onExecutionSnapshot}){
 const {addSigners,removeSigners}=useSigners();
 const [items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[allowAutomatic,setAllowAutomatic]=useState(false);
 const working=useRef(false),handled=useRef(null),completed=useRef(new Set()),initialRecords=useRef(false);
 useEffect(()=>{if(!items.length)return;if(!initialRecords.current){initialRecords.current=true;for(const m of items)if(m.status==='COMPLETED')completed.current.add(m.id);return;}for(const m of items){if(m.status==='COMPLETED'&&!completed.current.has(m.id)){completed.current.add(m.id);onComplete?.(m.proposal?.plan.newTokenId);}}},[items]);
 useEffect(()=>{onExecutionSnapshot?.(items.filter(m=>m.proposal&&((m.status==='WATCHING'&&m.mode==='AUTOMATIC'&&['QUEUED','RUNNING'].includes(m.job?.status))||((m.executionOnly||m.session)&&m.status==='COMPLETED'&&!m.signerRemovedAt))).map(m=>({...m.proposal.plan,accessCleanupPending:m.status==='COMPLETED'&&!m.signerRemovedAt})));},[items]);
 const load=async()=>setItems((await api('management/list')).items);
 useEffect(()=>{let live=true;const refresh=()=>api('management/list').then(r=>{if(live){setItems(r.items);}}).catch(e=>live&&setError(e.message));refresh();const timer=setInterval(refresh,10000);return()=>{live=false;clearInterval(timer);};},[account?.userId]);
 useEffect(()=>{if(!command||handled.current===command.id||busy)return;handled.current=command.id;run(async()=>{if(command.action==='SIMULATE'){onSimulation?.(await api('management/simulate',{wallet,tokenId:command.tokenId}));return;}if(command.action==='WATCH'){const watching=(await api('management/list')).items.find(m=>m.tokenId===command.tokenId&&!m.executionOnly&&m.status==='WATCHING'&&m.expiresAt>Date.now());if(!watching)await api('management/create',{wallet,tokenId:command.tokenId});return;}const current=(await api('management/list')).items.find(m=>m.tokenId===command.tokenId&&m.status==='WATCHING');if(!current)throw Error('Start monitoring this position first.');await api(command.action==='PAUSE'?'management/control':'management/assess',{id:current.id,...(command.action==='PAUSE'?{action:'PAUSE'}:{force:true})});});},[command?.id,busy]);
 async function run(work){if(working.current)return;working.current=true;setBusy(true);setError('');try{await work();await load();}catch(e){setError(e.message);}finally{working.current=false;setBusy(false);}}
 const sessions=items.filter(m=>m.tokenId===tokenId&&m.wallet?.toLowerCase()===wallet?.toLowerCase()&&!m.executionOnly);
 const current=sessions.find(m=>!['REVOKED','COMPLETED'].includes(m.status))||sessions[0];
 useEffect(()=>{onStatus?.(current||null);},[items,tokenId]);
 useEffect(()=>{setAllowAutomatic(false);},[tokenId]);
 const titles={HOLD:'Keep your current range',WIDEN:'Consider a wider range',EXIT:'Consider withdrawing'};
 async function start(){if(current&&!['REVOKED','COMPLETED'].includes(current.status)){if(current.proposal?.grant&&!current.signerRemovedAt)throw Error('Remove the previous signing access before starting a new session.');await api('management/control',{id:current.id,action:'REVOKE'});}await api('management/create',{wallet,tokenId});}
 return <section className="management-panel" aria-label="Position manager">
 <div className="panel-title"><h2>AI assistant</h2><span>{current?.status==='WATCHING'&&Date.now()<current.expiresAt?'Monitoring every minute':'Your next move'}</span></div>
 {tokenId&&<p className="small-note">USDC / WETH · 0.05% · Position #{tokenId}</p>}
 {error&&<p className="error-banner" role="alert">{error}</p>}
 {!isActive&&!current?<p className="small-note">Select an active position to get advice.</p>:!current?<><p>Let AI watch your range and suggest when to adjust.</p><div className="action-group"><button className="primary" disabled={busy} onClick={()=>run(start)}>Start monitoring</button></div></>:null}
 {current&&[current].map(m=>{const latest=m.assessments?.[0],expired=Date.now()>=m.expiresAt,ended=expired||['REVOKED','COMPLETED'].includes(m.status),blocked=latest?.graph.status!=='verified',executing=m.mode==='AUTOMATIC'&&['QUEUED','RUNNING'].includes(m.job?.status)&&m.status==='WATCHING';return <article className="advice-card" key={m.id}>
 <h3>{m.status==='COMPLETED'?'Adjustment complete':ended?'Monitoring session ended':m.status==='PAUSED'?'Monitoring paused':m.job?.status==='RUNNING'?'Adjusting your position':latest?titles[latest.result.action]:'Checking your position…'}</h3>
 <p>{m.status==='COMPLETED'?(m.signerRemovedAt?'Your new position is ready. Temporary access removed.':'Your new position is ready. Remove temporary access to finish.'):ended?(m.proposal?.grant&&!m.signerRemovedAt?'Remove expired signing access below, then start a new session.':'Start a new session when you are ready.'):m.status==='PAUSED'?(m.proposal?.grant&&Date.now()>=m.proposal.grant.expiresAt?'Signing access expired. Review the confirmed steps below and remove temporary access. An unfinished adjustment needs recovery.':'Review the latest checks before resuming.'):latest?latest.result.explanation:'You can keep using the page while AI checks your position.'}</p>
 {latest?.analysis&&<p className="small-note">{latest.analysis.demo?'Demo scenario evaluated':'Checked'} {new Date(latest.createdAt).toLocaleTimeString('en-US')}: WETH {fmt(latest.analysis.currentPrice)} USDC · {latest.analysis.inRange?'inside':'outside'} range {fmt(latest.analysis.scenarios?.[0]?.range?.low)}–{fmt(latest.analysis.scenarios?.[0]?.range?.high)}. {latest.result.action==='HOLD'?'No adjustment requested.':''}</p>}
 {latest?.executionReason&&<p role="alert" className="error-banner">{latest.executionReason}</p>}{latest?.result.widthPct&&<p className="small-note">Proposed range width: {latest.result.widthPct}% around the live price.</p>}{latest?.analysis.demo&&<p className="small-note">Hypothetical signal · live price remains {fmt(latest.analysis.observedPrice)} USDC. Any trade uses the real live price and the current authorization limits.</p>}
 {m.job?.status==='ARMED'&&m.status==='WATCHING'&&<details><summary>Testnet demo</summary><p>Ask AI to evaluate a hypothetical out-of-range price. If it recommends adjusting, a bounded session generates a fresh plan at the real live price. The real pool price is unchanged. Test tokens will move.</p><button disabled={busy||Date.now()>=m.proposal.grant.expiresAt} onClick={()=>run(()=>api('management/demo',{id:m.id}))}>Evaluate demo & execute if AI recommends</button><p>To demonstrate the executor even when AI chooses HOLD, explicitly run the already-approved plan. This is an operator demo trigger.</p><button disabled={busy||Date.now()>=m.proposal.grant.expiresAt} onClick={()=>run(()=>api('management/demo-execute',{id:m.id}))}>Execute approved plan · demo</button></details>}
 {m.job?.demo&&<p className="small-note">Execution source: {m.job.trigger==='DEMO_OPERATOR'?'operator-requested demo, not an AI recommendation':'hypothetical demo signal evaluated by AI'}.</p>}
 {m.job?.status==='ARMED'&&m.status==='WATCHING'&&<p className="small-note">Waiting for an AI adjustment recommendation. No trades sent.</p>}
 <div className="action-group">{ended?<button className="primary" disabled={busy||!isActive||!!m.proposal?.grant&&!m.signerRemovedAt} onClick={()=>run(start)}>Start new session</button>:m.status==='PAUSED'?<button className="primary" disabled={busy||!!m.proposal?.grant&&Date.now()>=m.proposal.grant.expiresAt} onClick={()=>run(()=>api('management/control',{id:m.id,action:'RESUME'}))}>Resume monitoring</button>:<><button className="primary" disabled={busy||executing} onClick={()=>run(()=>api('management/assess',{id:m.id,force:true}))}>{busy?'Checking…':'Check live price & advice'}</button><button disabled={busy} onClick={()=>run(()=>api('management/control',{id:m.id,action:'PAUSE'}))}>Pause</button></>}</div>
 <div className="automatic-toggle">{m.mode==='AUTOMATIC'&&m.status==='WATCHING'?<strong>Automatic execution authorized</strong>:<button disabled={busy||ended||m.status!=='WATCHING'||blocked||!!m.proposal} onClick={()=>run(async()=>{setAllowAutomatic(true);await api('management/session',{id:m.id});})}>Enable automatic execution</button>}<small>{m.signerRemovedAt?'Signing access removed':ended?'Session ended':m.status==='PAUSED'?'Paused · resume to continue within the existing authorization':m.proposal?.grant&&Date.now()>=m.proposal.grant.expiresAt?'Signing access expired':m.mode==='AUTOMATIC'&&m.status==='WATCHING'?'AI can generate and execute one fresh adjustment within this session':m.proposal?'Review the session limits below and confirm once':'Authorize one adjustment, including bounded wallet reserves'}</small></div><div className="automation-status"><span>Automatic adjustments</span>{blocked?<><strong>{latest?.graph.status==='not_configured'?'Data setup needed':latest?.graph.status==='syncing'?'Syncing pool history':'Checking pool data'}</strong><a href="/graph-setup.html" target="_blank" rel="noreferrer">Setup guide ↗</a></>:<button disabled={busy||!allowAutomatic||ended||m.status!=='WATCHING'||!!m.proposal} onClick={()=>run(()=>api('management/session',{id:m.id}))}>Review adjustment →</button>}</div>
 {m.proposal&&<details className="managed-proposal" open={m.mode!=='AUTOMATIC'}><summary>Adjustment details · {m.proposal.plan.calls.filter(c=>c.status==='confirmed').length}/{m.proposal.plan.calls.length} confirmed</summary><h3>{m.session?'Authorize AI range management':'Review this adjustment'}</h3>{m.session&&<p>AI may choose a new 5–50% range around the latest price and execute one adjustment. Up to 5 USDC and 0.004 WETH total may come from your position and wallet reserve. No swaps or ETH wrapping. Fixed owner recipient, 0.5% slippage, 0.0003 test ETH gas cap, 10-minute expiry. Monitoring follows the new position after completion; signing does not renew.</p>}{Date.now()>=m.proposal.plan.deadline*1000&&<p className="small-note">This proposal has expired. Remove any prepared access and start a new monitoring session before reviewing another adjustment.</p>}<p>{m.proposal.plan.details.usdc} USDC + {m.proposal.plan.details.weth} WETH · {m.session?'example amounts; final amounts depend on live price':'no fresh capital'}</p><p className="small-note">Base Sepolia only · owner receives all tokens · expires {new Date(m.proposal.plan.deadline*1000).toLocaleTimeString('en-US')} · total gas cap 0.0003 test ETH</p><ol>{m.proposal.plan.calls.map((c,i)=><li key={i}>{c.label} <small>{c.status||'Not sent'}</small>{c.hash&&<a href={'https://sepolia.basescan.org/tx/'+c.hash} target="_blank" rel="noreferrer">Receipt ↗</a>}</li>)}</ol>
 <p className="small-note">One wallet authorization covers all steps. The session keeps its original token, recipient, expiry and gas limits. A new range does not extend access.</p>{(m.session?['AI']:['OPERATOR','AI']).map(trigger=><button className={trigger==='OPERATOR'?'primary wide':''} key={trigger} disabled={busy||Date.now()>=m.proposal.plan.deadline*1000||m.mode==='AUTOMATIC'||m.status!=='WATCHING'} onClick={()=>run(async()=>{const ready=m.proposal.grant?m:await api('management/signer',{id:m.id});await ensureSignerAttached({api,addSigners,wallet,record:ready});await api('management/activate',{id:m.id,trigger});})}>{trigger==='OPERATOR'?'Confirm & adjust automatically':m.session?'Authorize AI management':'Confirm & let AI decide'}</button>)}{m.proposal.grant&&!m.signerRemovedAt&&<button disabled={busy} onClick={()=>run(async()=>{await api('management/control',{id:m.id,action:'PAUSE'}).catch(()=>{});const check=await api('management/cleanup-check',{id:m.id});if(!check.exclusive)throw Error('Other wallet access is present. Review signers before removing shared access.');await removeSigners({address:wallet});await api('management/signer-removed',{id:m.id});})}>Remove access & stop</button>}

 </details>}

 <details><summary>Monitoring details</summary><p>Position #{m.tokenId} · {m.mode==='AUTOMATIC'?'Limited automatic access':'Advice only'} · ends {new Date(m.expiresAt).toLocaleTimeString('en-US')} · {m.operations}/{m.maxOperations} adjustments.</p>{latest&&<p>Graph: {latest.graph.status}. {latest.gate||'Evidence checks passed.'}</p>}<button disabled={busy||m.status==='REVOKED'} onClick={()=>run(()=>api('management/control',{id:m.id,action:'REVOKE'}))}>End monitoring</button><details><summary>Activity log</summary>{[...(m.events||[])].reverse().map((e,i)=><p key={i}><small>{new Date(e.at).toLocaleTimeString('en-US')} · {e.event}</small>{e.detail}</p>)}</details></details>
 </article>;})}

 <details><summary>How AI management works</summary><p>Start monitoring → Enable automatic execution → Authorize AI management once. Every minute, changed pool data is sent to the model for a range decision and explanation. A WIDEN decision generates a fresh plan at live prices; Graph, token, recipient, slippage and gas checks must pass before the server signs.</p><p>For a reproducible MVP demo, open Testnet demo and evaluate the hypothetical out-of-range signal. It is labeled as simulated evidence; execution uses real test tokens and real prices. HOLD never trades. One adjustment per 10-minute signing session, followed by read-only monitoring.</p></details>
 </section>;
}
