import React,{useState,useEffect} from 'react';
export function PlanRehearsal({plan}){
 const [state,setState]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[amount,setAmount]=useState('800');
 async function api(input){const r=await fetch('/api/simulation',input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input.action==='INIT'?input:{requestId:crypto.randomUUID(),...input})}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'Local lab unavailable');return d;}
 useEffect(()=>{if(!state)return;let alive=true;const t=setInterval(()=>api().then(s=>{if(alive)setState(s);}).catch(e=>{if(alive)setError(e.message);}),1000);return()=>{alive=false;clearInterval(t);};},[Boolean(state)]);
 async function send(input){if(busy)return;setBusy(true);setError('');try{setState(await api(input));}catch(e){setError(e.message);}finally{setBusy(false);}}
 const working=state?.job&&['QUEUED','RUNNING','BLOCKED'].includes(state.job.status);
 const cents=Number(amount)*100;
 return <details><summary>Rehearse this range here — MOCK only</summary><p>This creates a NEW synthetic entry, not a real WIDEN transaction. No research text, wallet identity or token is copied into the shared local lab. Only the selected range and manual amount are sent; the lab treats them as unverified input. Existing lab state is reused, never reset.</p><button disabled={busy} onClick={()=>send({action:'INIT'})}>Open / restore local rehearsal</button>{error&&<p role="alert">{error}</p>}{state&&<><p>MOCK cash ${(state.cash/100).toFixed(2)} · LP ${(state.deployed/100).toFixed(2)} · {state.range?`${state.range.lower}–${state.range.upper}`:'No position'}</p><fieldset style={{minWidth:0}} disabled={busy||Boolean(working)}><label>Manual mock capital, whole dollars<input type="number" min="1" max="9998" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button onClick={()=>send({action:'FUND',amount:100000})}>Add $1,000 synthetic funding</button><button style={{whiteSpace:'normal',maxWidth:'100%'}} onClick={()=>send({action:'POLICY',maxCapital:100000,maxFee:500,maxDaily:10,maxSlippageBps:100,expiresInMinutes:60,automatic:false})}>Approve mock policy: $1,000 cap, $5 fee, 1% slippage, 10 actions, 60 minutes; no auto-management</button><button disabled={!Number.isInteger(cents)||cents<100||cents>999800} onClick={()=>send({action:'DRAFT',amount:cents,lower:Math.floor(plan.range.low),upper:Math.ceil(plan.range.high),reason:'User-selected research comparison range for a NEW mock entry. Unverified client transfer, not a real position instruction.'})}>Save selected range as a new mock draft</button></fieldset>{state.plan&&<div><p>MOCK v{state.plan.version} · {state.plan.status} · ${(state.plan.amount/100).toFixed(2)} · range {state.plan.range.lower}–{state.plan.range.upper}</p><button disabled={busy||state.plan.status!=='DRAFT'} onClick={()=>send({action:'CONFIRM_PLAN',version:state.plan.version})}>Confirm displayed mock version</button><button disabled={busy||state.plan.status!=='CONFIRMED'} onClick={()=>send({action:'EXECUTE_PLAN',version:state.plan.version})}>Execute confirmed MOCK entry</button></div>}<p>{state.job?`${state.job.kind} · ${state.job.status} · ${state.job.phase}/${state.job.phases.length} · ${state.job.reason||''}`:'No job'}</p><button disabled={busy} onClick={()=>send({action:'PAUSE'})}>Pause mock management</button><button disabled={busy} onClick={()=>send({action:'EXIT'})}>Exit mock position</button><p>Pause may block exit under the current simulator policy. For recovery, cancel unfinished work then explicitly approve a new mock policy. <a href="/lab">Advanced failure/recovery lab</a></p></>}</details>;
}
