import {pnlPercent} from '../src/scenario-values.mjs';
import React,{useEffect,useState} from 'react';
import {fmt} from './PoolViews.jsx';
export function PositionPerformance({wallet,position,api,onData,blockNumber}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let live=true;setData(null);setError('');setLoading(true);api('performance',{wallet,tokenId:position.tokenId}).then(r=>{if(live){setData(r);onData(r);}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[wallet,position.tokenId,blockNumber,attempt]);
 const verified=data?.accountingStatus==='verified';
 return <section className="position-performance" aria-label="Position earnings"><div className="panel-title"><h2>Position performance</h2><span>Only #{position.tokenId} · test USDC</span></div>{loading&&<p role="status">Checking deposits, withdrawals and earned fees onchain…</p>}{error&&<p role="alert" className="error-banner">{error} <button onClick={()=>setAttempt(a=>a+1)}>Retry accounting</button></p>}<div className="earnings-grid">{[['Total deposited',verified?data.depositedValue:null,'Valued when deposited'],['Value now',data?.currentValue,'Liquidity + claimable tokens'],['Received in wallet',verified?data.receivedValue:null,'Principal and fees collected'],['Profit / loss',verified?data.pnlBeforeGas:null,'Since creation · before gas']].map(([label,value,note])=><div key={label}><small>{label}</small><strong className={label==='Profit / loss'&&value!=null?(value<0?'loss':'gain'):''}>{value==null?'—':(label==='Profit / loss'&&value>0?'+':'')+fmt(value,label==='Profit / loss'?6:4)}</strong>{label==='Profit / loss'&&<small>{pnlPercent(value,data?.depositedValue)===null?'—':fmt(Number(pnlPercent(value,data.depositedValue).toFixed(4))||0,4)+'%'} of deposited capital</small>}<small>{note}</small></div>)}</div>{data&&<><div className="fee-summary"><div><small>Trading fees earned · collected + unclaimed</small><strong>{verified?fmt(data.fees.value,6):'—'} USDC</strong>{verified&&<small>{fmt(data.fees.usdc,8)} USDC + {fmt(data.fees.weth,10)} WETH</small>}</div><div><small>Claimable now · may include removed principal</small><strong>{fmt(data.claimableValue,6)} USDC</strong></div></div><div className={'range-risk '+(data.inRange?'':'risk-warning')}><strong>{data.inRange?'In range · eligible to earn swap fees':BigInt(position.liquidity)===0n?'Closed position · no active liquidity':'Outside the active range · not earning new swap fees'}</strong>{data.inRange&&<p>WETH can fall {fmt((1-data.range.low/data.price)*100)}% to {fmt(data.range.low)} or rise {fmt((data.range.high/data.price-1)*100)}% to {fmt(data.range.high)} USDC before leaving this range.</p>}</div>{!verified&&<p className="small-note">Full profit and fee accounting unavailable: {data.accountingReason} Missing values are not zero.</p>}<details><summary>How these numbers are calculated</summary><p>Profit / loss = value now + tokens already received − total deposited. Withdrawals include principal, so they are not all earnings. Historical cashflows use the pool price at the end of each transaction block. Current fee value uses today’s pool price.</p><p>Gas is excluded from profit / loss. Recorded transaction gas: {data.recordedGasEth||'unavailable'} ETH. Testnet prices are not market prices.</p><p>Verified snapshot: block {data.blockNumber}. <a href="https://blog.uniswap.org/uniswap-v3-math-primer-2" target="_blank" rel="noreferrer">Uniswap calculation reference ↗</a></p></details></>}</section>;
}
